[package]
name = "speller"
version = "0.1.0"
authors = ["Jacob Shaffer <jacob.shaffer@mining.komatsu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
rand = "0.7"
